---
name: "Cleanup ECR Image for Branch"
author: "Kenzi Stewart <kstewart@speareducation.com>"
description: "Checks that the application code is compatible with the specified PHP version"
inputs:
  git-ref:
    description: "Git branch or tag that corresponds with the ECR image"
    required: true
  ecr-registry:
    description: 12-digit ID of ECR registry, or the entire registry URL
    required: true
  ecr-repo:
    description: Name of ECR repository to act upon
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Cleanup ECR tag"
      shell: bash
      run: |
        ECR_REGISTRY_ID=$(echo "${{ inputs.ecr-registry }}" | sed -e 's/\..*$//g')
        APP_ENV="$(echo "${{ inputs.git-ref }}" | sed -e "s%releases/\(.*\)/.*$%\1%g")"
        ECR_IMAGE_NAME="$(echo "${{ inputs.git-ref }}" | sed -e "s%releases/${APP_ENV}/%${APP_ENV}-%g")"
        echo "Cleaning up release ${ECR_IMAGE_NAME}"
        aws ecr batch-delete-image \
          --registry-id "${ECR_REGISTRY_ID}" \
          --repository-name "${{ inputs.ecr-repo }}" \
          --image-ids "imageTag=${ECR_IMAGE_NAME}"

